-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

DROP TABLE IF EXISTS public.salons CASCADE;
DROP TABLE IF EXISTS public.employees CASCADE;
DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.procedures CASCADE;
DROP TABLE IF EXISTS public.additional_services CASCADE;
DROP TABLE IF EXISTS public.receipts CASCADE;
DROP TABLE IF EXISTS public.receipt_items CASCADE;
DROP TABLE IF EXISTS public.services CASCADE;
DROP TABLE IF EXISTS public.emp_serv CASCADE;

CREATE TABLE IF NOT EXISTS public.salons
(
    salon_id serial,
    name character varying(64) NOT NULL,
    address text NOT NULL,
    phone character varying(12) NOT NULL,
    PRIMARY KEY (salon_id),
    UNIQUE (name),
    UNIQUE (address),
    UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public.employees
(
    employee_id serial,
    name character varying(16) NOT NULL,
    surname character varying(32) NOT NULL,
    patronumic character varying(32),
    birthday date NOT NULL,
    passport character varying(12) NOT NULL,
    salon_id integer,
    phone character varying(12) NOT NULL,
    "position" character varying(64),
    manager_id integer,
    PRIMARY KEY (employee_id),
    UNIQUE (passport),
    UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    client_id serial,
    name character varying(32) NOT NULL,
    surname character varying(32) NOT NULL,
    patronumic character varying(32),
    birthday date,
    phone character varying(12) NOT NULL,
    email character varying(64),
    PRIMARY KEY (client_id),
    UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public.procedures
(
    procedure_id serial,
    description text NOT NULL,
    duration interval NOT NULL,
    service_id integer NOT NULL,
    PRIMARY KEY (procedure_id),
    UNIQUE (service_id)
);

CREATE TABLE IF NOT EXISTS public.additional_services
(
    add_service_id serial,
    service_id integer NOT NULL,
    is_season boolean NOT NULL,
    PRIMARY KEY (service_id),
    UNIQUE (add_service_id)
);

CREATE TABLE IF NOT EXISTS public.receipts
(
    receipt_id serial,
    client_id integer NOT NULL,
    total_sum numeric(10, 2) NOT NULL,
    date timestamp without time zone NOT NULL,
    PRIMARY KEY (receipt_id)
);

CREATE TABLE IF NOT EXISTS public.receipt_items
(
    receipt_id integer,
    emp_serv_id integer,
    quantity integer NOT NULL DEFAULT 1,
    price numeric(10, 2) NOT NULL,
    date timestamp without time zone NOT NULL,
    PRIMARY KEY (receipt_id, emp_serv_id)
        INCLUDE(emp_serv_id, receipt_id)
);

CREATE TABLE IF NOT EXISTS public.services
(
    service_id serial,
    name character varying(32) NOT NULL,
    price numeric(10, 2) NOT NULL,
    PRIMARY KEY (service_id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.emp_serv
(
    emp_serv_id serial,
    emp_id integer NOT NULL,
    serv_id integer NOT NULL,
    PRIMARY KEY (emp_serv_id),
    UNIQUE (emp_id, serv_id)
);

ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (manager_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.procedures
    ADD FOREIGN KEY (service_id)
    REFERENCES public.services (service_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.additional_services
    ADD FOREIGN KEY (service_id)
    REFERENCES public.services (service_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.receipts
    ADD FOREIGN KEY (client_id)
    REFERENCES public.clients (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.receipt_items
    ADD CONSTRAINT fk_receipt_items_receipts FOREIGN KEY (receipt_id)
    REFERENCES public.receipts (receipt_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.receipt_items
    ADD FOREIGN KEY (emp_serv_id)
    REFERENCES public.emp_serv (emp_serv_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.emp_serv
    ADD FOREIGN KEY (emp_id)
    REFERENCES public.employees (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.emp_serv
    ADD FOREIGN KEY (serv_id)
    REFERENCES public.services (service_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;



-- Заполнение таблицы salons
INSERT INTO public.salons (name, address, phone) VALUES ('Салон ООО «Казакова, Фадеев и Беспалов»', 'с. Добрянка, алл. Чайкиной, д. 286, 739319', '+77431047752');
INSERT INTO public.salons (name, address, phone) VALUES ('Салон РАО «Рыбакова Кудрявцева»', 'с. Радужный, пер. Новосельский, д. 56 к. 547, 866354', '+76638410325');
INSERT INTO public.salons (name, address, phone) VALUES ('Салон ИП «Русакова-Белоусова»', 'клх Калуга, ш. Центральное, д. 1 стр. 7/2, 549520', '+72175668808');
INSERT INTO public.salons (name, address, phone) VALUES ('Салон АО «Потапов»', 'г. Кизляр, алл. Вольная, д. 2/8 к. 8/8, 981460', '+70946042125');
INSERT INTO public.salons (name, address, phone) VALUES ('Салон Галкин Инкорпорэйтед', 'клх Коломна, пр. Подстанция, д. 55, 897910', '+74289487584');

-- Заполнение таблицы clients
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Елисей', 'Никифорова', 'Изотович', '1957-09-07', '+75805473083', 'regina_76@example.org');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Панкрат', 'Силин', 'Сергеевна', '1990-08-11', '+70216156911', 'eliseevazari@example.net');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Викторин', 'Горшкова', 'Владиславовна', '1995-03-12', '+75544196204', 'imamontov@example.org');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Елена', 'Щукина', 'Антипович', '1966-11-10', '+76068433597', 'ljubomir1981@example.com');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Автоном', 'Вишнякова', 'Марсович', '1972-11-18', '+77537159852', 'strelkoverofe@example.org');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Зоя', 'Гаврилова', 'Евгеньевна', '1985-04-25', '+75442563208', 'afinogen_48@example.com');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Иван', 'Терентьев', 'Васильевна', '2005-08-04', '+79590146210', 'arhippoljakov@example.net');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Автоном', 'Федотов', 'Елисеевич', '1979-11-20', '+77684579359', 'moke1981@example.net');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Авксентий', 'Мельникова', 'Эльдаровна', '1983-10-25', '+72069712278', 'kira01@example.net');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Любосмысл', 'Трофимова', 'Павловна', '1970-12-22', '+76415557728', 'ekulikov@example.net');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Добромысл', 'Калашников', 'Владленович', '1965-11-03', '+70711291671', 'tverdislavsazonov@example.com');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Онуфрий', 'Панфилов', 'Валерьевич', '2004-11-23', '+74384166065', 'dobroslav_1995@example.org');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Раиса', 'Казаков', 'Юрьевна', '1963-06-24', '+73546006163', 'anzhelika_2026@example.com');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Нина', 'Цветков', 'Ниловна', '1989-02-27', '+70599328174', 'wmuhina@example.net');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Арефий', 'Владимирова', 'Артемьевич', '1977-05-19', '+77533361526', 'panovfeofan@example.net');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Марина', 'Николаева', 'Марсович', '1956-09-23', '+73564548668', 'panovadarja@example.net');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Иосиф', 'Фадеева', 'Владиславовна', '1996-07-16', '+75972333255', 'sofronsidorov@example.org');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Парфен', 'Петрова', 'Олеговна', '2003-08-02', '+78614376332', 'iraida1975@example.org');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Авдей', 'Елисеева', 'Валериевна', '2004-07-30', '+77551346538', 'firssemenov@example.com');
INSERT INTO public.clients (name, surname, patronumic, birthday, phone, email) VALUES ('Евстигней', 'Сысоев', 'Гертрудович', '1957-02-19', '+71326466170', 'angelina1990@example.com');

-- Заполнение таблицы services
INSERT INTO public.services (name, price) VALUES ('Стрижка мужская', 3674.42);
INSERT INTO public.services (name, price) VALUES ('Стрижка женская', 2127.41);
INSERT INTO public.services (name, price) VALUES ('Окрашивание', 3557.2);
INSERT INTO public.services (name, price) VALUES ('Маникюр', 544.46);
INSERT INTO public.services (name, price) VALUES ('Педикюр', 3152.47);
INSERT INTO public.services (name, price) VALUES ('Массаж лица', 4645.63);
INSERT INTO public.services (name, price) VALUES ('Чистка лица', 969.18);
INSERT INTO public.services (name, price) VALUES ('Коррекция бровей', 1190.39);
INSERT INTO public.services (name, price) VALUES ('Эпиляция', 4145.46);
INSERT INTO public.services (name, price) VALUES ('Укладка', 4061.51);
INSERT INTO public.services (name, price) VALUES ('Пилинг', 1600.24);
INSERT INTO public.services (name, price) VALUES ('Парафинотерапия', 2848.95);
INSERT INTO public.services (name, price) VALUES ('Солярий', 1477.6);
INSERT INTO public.services (name, price) VALUES ('Мытье головы', 3194.49);
INSERT INTO public.services (name, price) VALUES ('Маска для волос', 973.36);

-- Заполнение таблицы procedures
INSERT INTO public.procedures (description, duration, service_id) VALUES ('Качественное выполнение услуги: Стрижка мужская', '2 hours', 1);
INSERT INTO public.procedures (description, duration, service_id) VALUES ('Качественное выполнение услуги: Стрижка женская', '1 hour', 2);
INSERT INTO public.procedures (description, duration, service_id) VALUES ('Качественное выполнение услуги: Окрашивание', '30 minutes', 3);
INSERT INTO public.procedures (description, duration, service_id) VALUES ('Качественное выполнение услуги: Маникюр', '30 minutes', 4);
INSERT INTO public.procedures (description, duration, service_id) VALUES ('Качественное выполнение услуги: Педикюр', '1 hour', 5);
INSERT INTO public.procedures (description, duration, service_id) VALUES ('Качественное выполнение услуги: Массаж лица', '2 hours', 6);
INSERT INTO public.procedures (description, duration, service_id) VALUES ('Качественное выполнение услуги: Чистка лица', '2 hours', 7);
INSERT INTO public.procedures (description, duration, service_id) VALUES ('Качественное выполнение услуги: Коррекция бровей', '1 hour 30 minutes', 8);
INSERT INTO public.procedures (description, duration, service_id) VALUES ('Качественное выполнение услуги: Эпиляция', '1 hour', 9);
INSERT INTO public.procedures (description, duration, service_id) VALUES ('Качественное выполнение услуги: Укладка', '1 hour', 10);

-- Заполнение таблицы additional_services
INSERT INTO public.additional_services (service_id, is_season) VALUES (11, TRUE);
INSERT INTO public.additional_services (service_id, is_season) VALUES (12, FALSE);
INSERT INTO public.additional_services (service_id, is_season) VALUES (13, TRUE);
INSERT INTO public.additional_services (service_id, is_season) VALUES (14, TRUE);
INSERT INTO public.additional_services (service_id, is_season) VALUES (15, FALSE);

-- Заполнение таблицы employees
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Милован', 'Воронов', 'Валериевна', '1978-10-14', '0003979401', 2, '+71884677884', 'Стажер', NULL);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Роман', 'Макарова', 'Ильясович', '1975-08-10', '7455353609', 1, '+73892515086', 'Стажер', NULL);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Ипполит', 'Авдеева', 'Вячеславович', '1968-12-21', '8168647049', 3, '+77852619000', 'Стажер', NULL);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Симон', 'Зиновьева', 'Тимурович', '2005-06-15', '9059034401', 4, '+72811911931', 'Мастер', 1);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Казимир', 'Волков', 'Теймуразович', '1966-09-29', '6772147736', 5, '+78906703948', 'Мастер', 2);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Панкрат', 'Пестова', 'Бенедиктович', '1971-05-07', '7736291491', 2, '+72970676255', 'Старший мастер', 2);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Порфирий', 'Морозов', 'Фокич', '1996-01-01', '8605604086', 5, '+79572507025', 'Администратор', 1);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Павел', 'Панова', 'Антоновна', '1965-05-02', '1815380726', 4, '+76618546731', 'Мастер', 3);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Ипат', 'Стрелкова', 'Зиновьевич', '1983-10-12', '9838176417', 2, '+75217790347', 'Мастер', 1);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Фотий', 'Суворов', 'Дмитриевич', '1966-04-01', '7519794640', 1, '+78636028758', 'Стажер', 2);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Милан', 'Зайцев', 'Измаилович', '1986-08-22', '9349783908', 1, '+73349357659', 'Мастер', 3);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Доброслав', 'Мишин', 'Захаровна', '2000-09-26', '5170582843', 3, '+75837778953', 'Стажер', 3);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Феофан', 'Кабанов', 'Феликсович', '1966-08-16', '3393517319', 3, '+79560307230', 'Топ-стилист', 3);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Фрол', 'Титов', 'Фёдорович', '1969-11-07', '3344558399', 1, '+72231085299', 'Мастер', 3);
INSERT INTO public.employees (name, surname, patronumic, birthday, passport, salon_id, phone, "position", manager_id) VALUES ('Юлий', 'Меркушев', 'Венедиктович', '1994-10-20', '0460538092', 1, '+71729396531', 'Мастер', 3);

-- Заполнение таблицы emp_serv
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (1, 9);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (1, 14);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (2, 12);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (2, 1);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (2, 9);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (2, 7);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (2, 3);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (3, 9);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (3, 5);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (3, 13);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (3, 6);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (3, 11);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (4, 10);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (4, 3);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (4, 6);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (4, 14);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (4, 9);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (5, 15);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (5, 11);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (5, 9);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (5, 3);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (6, 6);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (6, 13);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (7, 13);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (7, 14);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (8, 8);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (8, 3);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (8, 9);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (8, 7);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (9, 4);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (9, 13);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (10, 1);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (10, 15);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (10, 5);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (11, 14);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (11, 5);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (11, 4);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (11, 12);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (11, 6);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (12, 7);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (12, 8);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (13, 13);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (13, 10);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (13, 8);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (13, 2);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (14, 3);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (14, 8);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (14, 6);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (14, 5);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (15, 10);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (15, 9);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (15, 4);
INSERT INTO public.emp_serv (emp_id, serv_id) VALUES (15, 2);

-- Заполнение таблиц receipts и receipt_items
INSERT INTO public.receipts (client_id, total_sum, date) VALUES (12, 12728.99, '2025-05-20 16:41:51');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (1, 43, 1, 4061.51, '2025-05-20 16:41:51');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (1, 30, 1, 544.46, '2025-05-20 16:41:51');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (1, 13, 2, 4061.51, '2025-05-20 16:41:51');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (9, 6055.20, '2025-09-01 14:54:35');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (2, 32, 1, 3674.42, '2025-09-01 14:54:35');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (2, 44, 2, 1190.39, '2025-09-01 14:54:35');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (14, 1190.39, '2026-01-17 21:00:31');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (3, 44, 1, 1190.39, '2026-01-17 21:00:31');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (9, 4326.55, '2025-04-10 12:42:19');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (4, 23, 1, 1477.6, '2025-04-10 12:42:19');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (4, 3, 1, 2848.95, '2025-04-10 12:42:19');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (9, 7798.10, '2025-05-19 04:42:36');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (5, 15, 1, 4645.63, '2025-05-19 04:42:36');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (5, 34, 1, 3152.47, '2025-05-19 04:42:36');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (10, 10308.89, '2025-04-08 23:56:16');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (6, 25, 1, 3194.49, '2025-04-08 23:56:16');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (6, 21, 2, 3557.2, '2025-04-08 23:56:16');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (13, 9706.89, '2026-03-04 06:40:25');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (7, 23, 2, 1477.6, '2026-03-04 06:40:25');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (7, 25, 1, 3194.49, '2026-03-04 06:40:25');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (7, 46, 1, 3557.2, '2026-03-04 06:40:25');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (2, 3605.01, '2026-02-21 12:50:43');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (8, 24, 1, 1477.6, '2026-02-21 12:50:43');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (8, 45, 1, 2127.41, '2026-02-21 12:50:43');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (18, 973.36, '2025-12-13 03:46:00');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (9, 18, 1, 973.36, '2025-12-13 03:46:00');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (6, 3100.77, '2026-01-06 12:08:57');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (10, 53, 1, 2127.41, '2026-01-06 12:08:57');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (10, 18, 1, 973.36, '2026-01-06 12:08:57');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (17, 11320.96, '2025-07-27 15:53:37');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (11, 8, 1, 4145.46, '2025-07-27 15:53:37');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (11, 3, 2, 2848.95, '2025-07-27 15:53:37');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (11, 31, 1, 1477.6, '2025-07-27 15:53:37');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (6, 2566.52, '2026-03-21 01:28:35');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (12, 52, 2, 544.46, '2026-03-21 01:28:35');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (12, 23, 1, 1477.6, '2026-03-21 01:28:35');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (19, 4747.59, '2025-12-07 09:08:34');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (13, 41, 1, 1190.39, '2025-12-07 09:08:34');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (13, 7, 1, 3557.2, '2025-12-07 09:08:34');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (14, 9291.26, '2025-06-07 18:22:41');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (14, 22, 2, 4645.63, '2025-06-07 18:22:41');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (17, 1477.60, '2025-10-02 09:23:11');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (15, 24, 1, 1477.6, '2025-10-02 09:23:11');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (10, 14414.15, '2025-06-09 21:38:14');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (16, 5, 2, 4145.46, '2025-06-09 21:38:14');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (16, 42, 1, 1477.6, '2025-06-09 21:38:14');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (16, 22, 1, 4645.63, '2025-06-09 21:38:14');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (6, 7348.84, '2025-10-14 03:34:13');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (17, 32, 2, 3674.42, '2025-10-14 03:34:13');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (19, 10737.70, '2025-09-10 16:01:30');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (18, 6, 1, 969.18, '2025-09-10 16:01:30');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (18, 1, 2, 4145.46, '2025-09-10 16:01:30');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (18, 23, 1, 1477.6, '2025-09-10 16:01:30');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (19, 12848.46, '2025-12-28 01:19:24');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (19, 39, 2, 4645.63, '2025-12-28 01:19:24');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (19, 14, 1, 3557.2, '2025-12-28 01:19:24');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (10, 14595.86, '2026-03-12 01:10:58');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (20, 28, 2, 4145.46, '2026-03-12 01:10:58');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (20, 36, 2, 3152.47, '2026-03-12 01:10:58');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (2, 7538.87, '2025-11-07 23:58:58');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (21, 38, 1, 2848.95, '2025-11-07 23:58:58');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (21, 30, 1, 544.46, '2025-11-07 23:58:58');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (21, 8, 1, 4145.46, '2025-11-07 23:58:58');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (6, 13640.64, '2025-11-30 13:04:38');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (22, 17, 1, 4145.46, '2025-11-30 13:04:38');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (22, 47, 2, 1190.39, '2025-11-30 13:04:38');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (22, 46, 2, 3557.2, '2025-11-30 13:04:38');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (7, 6110.39, '2025-07-21 14:49:24');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (23, 40, 1, 969.18, '2025-07-21 14:49:24');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (23, 18, 2, 973.36, '2025-07-21 14:49:24');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (23, 16, 1, 3194.49, '2025-07-21 14:49:24');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (13, 6388.98, '2025-06-18 00:01:40');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (24, 25, 1, 3194.49, '2025-06-18 00:01:40');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (24, 35, 1, 3194.49, '2025-06-18 00:01:40');

INSERT INTO public.receipts (client_id, total_sum, date) VALUES (6, 969.18, '2025-10-03 11:18:52');
INSERT INTO public.receipt_items (receipt_id, emp_serv_id, quantity, price, date) VALUES (25, 6, 1, 969.18, '2025-10-03 11:18:52');