-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public.room CASCADE;
DROP TABLE IF EXISTS public.client CASCADE;
DROP TABLE IF EXISTS public.rack CASCADE;
DROP TABLE IF EXISTS public.product CASCADE;
DROP TABLE IF EXISTS public.placement CASCADE;
DROP TABLE IF EXISTS public.contract CASCADE;
DROP TABLE IF EXISTS public.tenancy CASCADE;

CREATE TABLE IF NOT EXISTS public.room
(
    id_room smallint,
    room_name character varying(100) NOT NULL,
    capacity_volume numeric(10, 2) NOT NULL,
    temp_conditions smallint NOT NULL,
    humidity_conditions smallint NOT NULL,
    PRIMARY KEY (id_room),
    UNIQUE (room_name)
);

CREATE TABLE IF NOT EXISTS public.client
(
    id_client serial,
    company_name character varying(255) NOT NULL,
    bank_details text NOT NULL,
    PRIMARY KEY (id_client),
    UNIQUE (bank_details, company_name)
);

CREATE TABLE IF NOT EXISTS public.rack
(
    id_rack serial,
    rack_number character varying(20),
    storage_slots integer NOT NULL,
    max_load numeric(10, 2) NOT NULL,
    height numeric(10, 3) NOT NULL,
    width numeric(10, 3) NOT NULL,
    length numeric(10, 3) NOT NULL,
    id_room smallint,
    PRIMARY KEY (id_rack),
    UNIQUE (rack_number, id_room)
);

CREATE TABLE IF NOT EXISTS public.product
(
    id_product bigserial,
    description text,
    length numeric(10, 3) NOT NULL,
    width numeric(10, 3) NOT NULL,
    height numeric(10, 3) NOT NULL,
    weight numeric(10, 2) NOT NULL,
    arrival_date date,
    temp_conditions smallint,
    humidity_conditions smallint,
    "position" integer,
    id_contract bigint NOT NULL,
    PRIMARY KEY (id_product)
)

WITH (
    FILLFACTOR = 70
);

CREATE TABLE IF NOT EXISTS public.placement
(
    id_placement bigserial,
    id_product bigint NOT NULL,
    id_tenancy integer,
    PRIMARY KEY (id_placement),
    UNIQUE (id_product)
)

WITH (
    FILLFACTOR = 70
);

CREATE TABLE IF NOT EXISTS public.contract
(
    id_contract bigserial,
    contract_number character varying(63) NOT NULL,
    end_date date NOT NULL,
    PRIMARY KEY (id_contract),
    UNIQUE (contract_number)
);

CREATE TABLE IF NOT EXISTS public.tenancy
(
    id_tenancy serial,
    id_client integer,
    id_rack integer NOT NULL,
    PRIMARY KEY (id_tenancy),
    UNIQUE (id_rack)
);

ALTER TABLE IF EXISTS public.rack
    ADD FOREIGN KEY (id_room)
    REFERENCES public.room (id_room) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.product
    ADD FOREIGN KEY (id_contract)
    REFERENCES public.contract (id_contract) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.placement
    ADD FOREIGN KEY (id_tenancy)
    REFERENCES public.tenancy (id_tenancy) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.placement
    ADD FOREIGN KEY (id_product)
    REFERENCES public.product (id_product) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tenancy
    ADD FOREIGN KEY (id_client)
    REFERENCES public.client (id_client) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tenancy
    ADD FOREIGN KEY (id_rack)
    REFERENCES public.rack (id_rack) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.room
    ADD CONSTRAINT ck_room_capacity_volume_positive
    CHECK (capacity_volume > 0);

ALTER TABLE IF EXISTS public.room
    ADD CONSTRAINT ck_room_temp_conditions_valid
    CHECK (temp_conditions::integer > 0 AND temp_conditions::integer < 100);

ALTER TABLE IF EXISTS public.room
    ADD CONSTRAINT ck_room_humidity_conditions_valid
    CHECK (humidity_conditions::integer > 0 AND humidity_conditions::integer < 100);

ALTER TABLE IF EXISTS public.rack
    ADD CONSTRAINT ck_rack_storage_slots_positive
    CHECK (storage_slots > 0);

ALTER TABLE IF EXISTS public.rack
    ADD CONSTRAINT ck_rack_max_load_positive
    CHECK (max_load > 0);

ALTER TABLE IF EXISTS public.rack
    ADD CONSTRAINT ck_rack_dimensions_positive
    CHECK (height > 0 AND width > 0 AND length > 0);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT ck_product_dimensions_positive
    CHECK (length > 0 AND width > 0 AND height > 0);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT ck_product_weight_positive
    CHECK (weight > 0);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT ck_product_arrival_date_not_future
    CHECK (arrival_date <= CURRENT_DATE);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT ck_product_temp_conditions_valid
    CHECK (temp_conditions::integer > 0 AND temp_conditions::integer < 100);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT ck_product_humidity_conditions_valid
    CHECK (humidity_conditions::integer > 0 AND humidity_conditions::integer < 100);

ALTER TABLE IF EXISTS public.contract
    ADD CONSTRAINT ck_contract_end_date_future
    CHECK (end_date > CURRENT_DATE);

END;